#Offset is between -1:1
#z-location is between 0:1
---
blocked_hole:
  type: 'blocked_hole'
  type_specific:
    dummy: ''
    wall: 'right'
    corridor_type: 'empty'
floor:
  type: 'floor'
  type_specific:
    name: 'floor'
    texture: 'Gazebo/Grey'
    corridor_type: 'empty'