#Offset is between -1:1
#z-location is between 0:1
---
blocked_hole:
  type: 'blocked_hole'
  type_specific:
    dummy: ''
    wall: 'right'
arc:
  type: 'passway'
  number: 20
  type_specific:
    name: 'arc'
    texture: 'Gazebo/DarkGrey'
    offset: 1
ceiling:
  type: 'ceiling'
  type_specific:
    name: 'ceiling'
    dummy: ''
human:
  type: 'obstacle'
  number: 15
  type_specific:
    dummy: ''
    name: 'person_standing'
    side_offset: 0.9
floor:
  type: 'floor'
  type_specific:
    name: 'floor'
    texture: 'Gazebo/DarkGrey'
