#Offset is between -1:1
#z-location is between 0:1
---
poster:
  type: 'panel'
  number: 40
  type_specific:
    height: 1
    width: 0.7
    thickness: 0.02
    z_location: 0.8
    offset: 0
    wall: 'right'
    texture: 'Gazebo/Yellow'
radiator:
  type: 'panel'
  number: 50
  type_specific:
    height: 0.6
    width: 1
    thickness: 0.1
    z_location: 0.1
    offset: 0
    texture: 'Gazebo/Grey'
doorway:
  type: 'passway'
  number: 20
  type_specific:
    name: 'doorway'
    offset: 1
    texture: 'Gazebo/White'
floor:
  type: 'floor'
  type_specific:
    name: 'floor'
    texture: 'Gazebo/DarkGrey'
ceiling:
  type: 'ceiling'
  type_specific:
    name: 'pipes'
    dummy: ''
