# Offset is between -1:1
# z-location is between 0:1
# everything that is not specified is randomly selected.
---
radiator:
  type: 'panel'
  number: 8
  type_specific:
    height: 0.6
    width: 1
    thickness: 0.1
    z_location: 0.1
    offset: 0
    texture: 'Gazebo/Grey'
doorway:
  type: 'passway'
  number: 10
  type_specific:
    name: 'doorway'
    texture: 'Gazebo/Grey'
person_standing:
  type: 'obstacle'
  number: 15
  type_specific:
    dummy: ''
    name: 'person_standing'
    side_offset: 0.7
floor:
  type: 'floor'
  type_specific:
    name: 'floor'
    texture: 'Gazebo/Yellow'