# Offset is between -1:1
# z-location is between 0:1
# everything that is not specified is randomly selected.
---
poster:
  type: 'panel'
  number: 8
  type_specific:
    height: 1
    width: 0.7
    thickness: 0.02
    z_location: 0.8
    offset: 0
    texture: 'Gazebo/Blue'
ceiling:
  type: 'ceiling'
  type_specific:
    name: 'ceiling'
    dummy: ''
bookshelf:
  type: 'obstacle'
  number: 15
  type_specific:
    dummy: ''
    name: 'bookshelf'
    side_offset: 0.9
floor:
  type: 'floor'
  type_specific:
    name: 'floor'
    texture: 'Gazebo/Grey'