# Offset is between -1:1
# z-location is between 0:1
# everything that is not specified is randomly selected.
---
arc:
  type: 'passway'
  number: 1
  type_specific:
    dummy: ''
    name: 'arc'
    texture: 'Gazebo/White'