#Offset is between -1:1
#z-location is between 0:1
---
radiator:
  type: 'panel'
  number: 1
  type_specific:
    height: 0.6
    width: 1
    thickness: 0.1
    z_location: 0.1
    offset: 0
    texture: 'Gazebo/Grey'