# Offset is between -1:1
# z-location is between 0:1
# everything that is not specified is randomly selected.
---
extension_0:
  type: 'panel'
  number: 1
  type_specific:
    dummy: ''
extension_1:
  type: 'panel'
  number: 1
  type_specific:
    dummy: ''