#Offset is between -1:1
#z-location is between 0:1
---
radiator:
  type: 'panel'
  number: 30
  type_specific:
    dummy: ''
poster:
  type: 'panel'
  number: 30
  type_specific:
    dummy: ''
arc:
  type: 'passway'
  number: 20
  type_specific:
    name: 'arc'
    offset: 1
doorway:
  type: 'passway'
  number: 0
  type_specific:
    name: 'doorway'
    offset: 1
floor:
  type: 'floor'
  type_specific:
    name: 'floor'
    texture: 'Gazebo/DarkGrey'
# ceiling:
#   type: 'ceiling'
#   type_specific:
#     name: 'ceiling'
#     dummy: ''
pipes:
  type: 'ceiling'
  type_specific:
    name: 'pipes'
    dummy: ''
# blocked_hole:
#   type: 'blocked_hole'
#   type_specific:
#     dummy: ''