# debug is loaded to avoid the evaluation code to cut down the experiment too early.
# Maximum duration and distance is not defined, avoiding the experiment to stop too soon.
delay_evaluation: 1 
# Minimum depth is lower than fsm can measure so it will not detect collisions.
min_depth: 0.1 
starting_height: 1