takeoff: /takeoff
land: /land
emergency: /emergency
flattrim: /flattrim
control: /cmd_vel
rgb_image: /kinect/kinect/rgb/image_raw
depth_image: /kinect/kinect/depth/image_raw
gt_info: /ground_truth/state