network: tiny_v2
learning_rate: 0.001
optimizer: gradientdescent
speed: 0.3
action_bound: 0.6
discrete: True
empty_buffer: True
buffer_size: -1
batch_size: -1
break_and_turn: True
epsilon: 0.5
epsilon_decay: 0.9
lifelonglearning: True
minimum_collision_free_duration: 30