network: tiny_v2
learning_rate: 0.01
optimizer: gradientdescent
speed: 0.3
action_bound: 0.6
discrete: True
empty_buffer: True
buffer_size: -1
batch_size: -1
break_and_turn: True
epsilon: 0.5
epsilon_decay: 0.1
hard_replay_buffer: True
hard_batch_size: 50
update_importance_weights: True
minimum_collision_free_duration: 3