network: tiny_v2
learning_rate: 0.001
optimizer: gradientdescent
# POLICY
speed: 0.3
action_bound: 0.6
discrete: True
break_and_turn: True
epsilon: 0.
epsilon_decay: 0.1
# TRAINING
empty_buffer: True
buffer_size: 100
batch_size: 30
max_gradient_steps: 2
backward_pass_every: batch
# INITIALIZATION
# continue_training: True
# load_config: True
scratch: True
# LLL
# minimum_collision_free_distance: 9
# lifelonglearning: False
# update_importance_weights: False
# HARD REPLAY BUFFER
# hard_replay_buffer: False
# hard_batch_size: 50